### ISSUE TITLE
[Feature] Handle stmw instructions with non-existant lbl

### ISSUE THREAD

**Issue by dreamsyntax** [InusualZ/dadosod#1]
Failed to parse instruction at text.s line 1098614: stmw r4, lbl_805F96F0@sda21(r2)

Sample
```
/* 8039CAC8 00396388  7C 12 42 A6 */	mfspr r0, 274
/* 8039CACC 0039638C  90 02 00 0C */	stw r0, lbl_805F96EC@sda21(r2)
/* 8039CAD0 00396390  BC 82 00 10 */	stmw r4, lbl_805F96F0@sda21(r2)
/* 8039CAD4 00396394  7F 7A 02 A6 */	mfspr r27, 26
/* 8039CAD8 00396398  7F 88 02 A6 */	mflr r28
```

lbl_805F96F0 does not exist within the text.s
Only within sdata.s
```
lbl_805ECD50:

	# ROM: 0x575650
	.4byte lbl_805F96F0
	.4byte 0
```

Proposal: add flag/support for skip/nop patching if the lbl does not exist

**Comment by InusualZ** [comment]
> Failed to parse instruction at text.s line 1098614: stmw r4, lbl_805F96F0@sda21(r2)

What program throw you this error?
What game are you trying to disassemble?

The label being in another section is totally fine, so I don't understand who could be giving you that error. I know that MWCC's assembler have some issue with the `stmw` and `lmw` instructions so that could be it?

**Comment by dreamsyntax** [comment]
Ah sorry, I just realized I opened this on the dadosod repo when I meant to open it on m2c's repo

> What program throw you this error? What game are you trying to disassemble?

python.exe .\m2c.py --target ppc-mwcc-c++ .\DOL\asm\text.s

 > What game are you trying to disassemble?

GUPE8P

> The label being in another section is totally fine, so I don't understand who could be giving you that error. I know that MWCC's assembler have some issue with the `stmw` and `lmw` instructions so that could be it?

^ Most likely
